### ISSUE TITLE
Make devel branch work on FreeBSD

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#223]
v0.6 branch works on FreeBSD but later branches doesn't.  We need to make at least v0.8 working as TLS is needed for security.  Current xrdp has lots of GNU/Linux specific codes. 

I'm working on to get better FreeBSD support.  Let me manage TODO list here.
## TODO list
- [x] #226 PAM authentication (OpenPAM is used in FreeBSD)
- [ ] `--disable-pam` fails to build
- [x] session.c setlogin(2) patch #251 
- [ ] make fuse working (drive, clipboard file redirection)
- [x] #146 os_calls.c: g_sck_get_peer_cred() needs to be patched for FreeBSD 
- [x] init script, instfiles #252 
- [ ] #30 ipv6 support
- [x] merge downstream local patches 
- [x] TLS #248 #249

**Comment by metalefty** [comment]
Except for some features such as FUSE, xrdp is working on FreeBSD.
